In [42]:
import pandas as pd
df = pd.read_csv('car_price_performance.csv')
df.head()

,Brand,Price,Horsepower,Fuel Efficiency,Scaled Horsepower,Scaled Fuel Efficiency,Encoded Brand,Scaled Encoded Brand
0,Brand C,91942,382,15.3,0.7050,0.212,5,0.625
1,Brand A,70075,197,32.6,0.2425,0.904,3,0.375
2,Brand C,84524,188,34.9,0.2200,0.996,5,0.625
3,Brand E,68939,258,15.1,0.3950,0.204,1,0.125
4,Brand X,66505,277,13.0,0.4425,0.120,7,0.875

In [43]:
avg_price = df.groupby('Brand')['Price'].mean().sort_values().index
avg_price

Index(['Brand W', 'Brand E', 'Brand Y', 'Brand A', 'Brand B', 'Brand C',
       'Brand Z', 'Brand X', 'Brand D'],
      dtype='object', name='Brand')

In [44]:
brand_mapping = {brand: i for i, brand in enumerate(avg_price)}
df['Encoded Brand']=df['Brand'].map(brand_mapping)
# label encoding with average
df.head()

,Brand,Price,Horsepower,Fuel Efficiency,Scaled Horsepower,Scaled Fuel Efficiency,Encoded Brand,Scaled Encoded Brand
0,Brand C,91942,382,15.3,0.7050,0.212,5,0.625
1,Brand A,70075,197,32.6,0.2425,0.904,3,0.375
2,Brand C,84524,188,34.9,0.2200,0.996,5,0.625
3,Brand E,68939,258,15.1,0.3950,0.204,1,0.125
4,Brand X,66505,277,13.0,0.4425,0.120,7,0.875

In [45]:
 import pandas as pd
 for column in ['Encoded Brand']:
    min_val = df[column].min()
    max_val = df[column].max()
    df['Scaled ' + column] = (df[column] - min_val) / (max_val - min_val)

df.head()

,Brand,Price,Horsepower,Fuel Efficiency,Scaled Horsepower,Scaled Fuel Efficiency,Encoded Brand,Scaled Encoded Brand
0,Brand C,91942,382,15.3,0.7050,0.212,5,0.625
1,Brand A,70075,197,32.6,0.2425,0.904,3,0.375
2,Brand C,84524,188,34.9,0.2200,0.996,5,0.625
3,Brand E,68939,258,15.1,0.3950,0.204,1,0.125
4,Brand X,66505,277,13.0,0.4425,0.120,7,0.875

In [46]:
import pandas as pd

for column in ['Horsepower', 'Fuel Efficiency']:

    min_val = df[column].min()
    max_val = df[column].max()

    df['Scaled ' + column] = (df[column] - min_val) / (max_val - min_val)

df.head()

,Brand,Price,Horsepower,Fuel Efficiency,Scaled Horsepower,Scaled Fuel Efficiency,Encoded Brand,Scaled Encoded Brand
0,Brand C,91942,382,15.3,0.7050,0.212,5,0.625
1,Brand A,70075,197,32.6,0.2425,0.904,3,0.375
2,Brand C,84524,188,34.9,0.2200,0.996,5,0.625
3,Brand E,68939,258,15.1,0.3950,0.204,1,0.125
4,Brand X,66505,277,13.0,0.4425,0.120,7,0.875

In [50]:
df['Performance Index'] = df['Horsepower'] * 0.7 + df['Fuel Efficiency'] * 0.3 / df['Price']
df.head()

,Brand,Price,Horsepower,Fuel Efficiency,Scaled Horsepower,Scaled Fuel Efficiency,Encoded Brand,Scaled Encoded Brand,Performance Index
0,Brand C,91942,382,15.3,0.7050,0.212,5,0.625,267.400050
1,Brand A,70075,197,32.6,0.2425,0.904,3,0.375,137.900140
2,Brand C,84524,188,34.9,0.2200,0.996,5,0.625,131.600124
3,Brand E,68939,258,15.1,0.3950,0.204,1,0.125,180.600066
4,Brand X,66505,277,13.0,0.4425,0.120,7,0.875,193.900059

In [51]:
df.to_csv('car_price_performance.csv', index=False)
df.head()

,Brand,Price,Horsepower,Fuel Efficiency,Scaled Horsepower,Scaled Fuel Efficiency,Encoded Brand,Scaled Encoded Brand,Performance Index
0,Brand C,91942,382,15.3,0.7050,0.212,5,0.625,267.400050
1,Brand A,70075,197,32.6,0.2425,0.904,3,0.375,137.900140
2,Brand C,84524,188,34.9,0.2200,0.996,5,0.625,131.600124
3,Brand E,68939,258,15.1,0.3950,0.204,1,0.125,180.600066
4,Brand X,66505,277,13.0,0.4425,0.120,7,0.875,193.900059